server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/showtime?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yjxsz2001
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    # 控制台打印 SQL（开发环境）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  # 实体类存放位置（MyBatis-Plus 自动映射时需要）
  # type-aliases-package: com.showtime.entity
